# Generated by Django 5.1.4 on 2025-01-22 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shoping", "0001_initial"),
    ]

    operations = []
